{% set name = "json-flattener" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/json_flattener-{{ version }}.tar.gz
  sha256: 84cf8523045ffb124301a602602201665fcb003a171ece87e6f46ed02f7f0c15

build:
  entry_points:
    - jfl=json_flattener.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - click
    - pyyaml

test:
  imports:
    - json_flattener
  commands:
    - pip check
    - jfl --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cmungall/json-flattener
  summary: Python library for denormalizing nested dicts or json objects to tables and back
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dstansby
